language: shell
sudo: false
cache:
  bundler: true
deploy:
- provider: s3
  access_key_id: AKIAIT4X4NDGM2WVL6VA
  secret_access_key: &1
    secure: m+UKHDt++XxatsRBu075nWhWMUBJOsiWh70Nipdkmt1srsom3sMTi/r50a2jBPOMzYwm2Oc+CNscsUfIiHHaxSzVf32Uq0RLTK9kUZ7T8sqjoT0wvJ8pt+zEt0S2GBRMjzvj0C0S+byaX/9JJOmu0lrLxvOWm6tTPM8XuC4LM6g=
  local_dir: site
  skip_cleanup: true
  bucket: www.octoblu.com
  endpoint: www.octoblu.com.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  on:
    branch: master
