language: shell
sudo: false
cache:
  bundler: true
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: &1
    secure: "aQ3tqD9yWgsqa2/4u0l6xDti68IusJGM0u7H6uquF1lxKpdqV+8jysaACs+l01DGYV2mJZMk9Je1XxYEcKhDKTuL8/npgFIUzWCaHYi+VioE413IlX1Ecl1W2LeKZLG23ITc5d+8whgQ0HizlSdrFH06OSMeHA3nzFwujOAqAk8="
  local_dir: site
  skip_cleanup: true
  bucket: www.octoblu.com
  endpoint: www.octoblu.com.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  on:
    branch: master
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: *1
  local_dir: site
  skip_cleanup: true
  bucket: www-staging.octoblu.com
  endpoint: www-staging.octoblu.com.s3-website-us-west-2.amazonaws.com
  region: us-west-2
  on:
    branch: staging
